niclog/urls.py
from django.contrib import admin
from django.urls import path, include
from tourlog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tourlog.urls')),  # Include with the app namespace
    path('reg.html', views.reg, name='reg'),
    path('home/',views.home,name='home'),
    path('updateData/<int:EmpCode>', views.updateData, name='updateData'),
    path('final/<int:EmpCode>', views.final, name='final'),

]

tourlog/urls.py
from django.urls import path
from . import views
# from .views import register_view


app_name = 'tourlog'  # Add this line to define the app namespace

urlpatterns = [
    path('', views.home, name='home'),
    path('signup.html', views.signup, name='signup'),
    path('reg.html', views.reg, name='reg'),
    path('logout',views.logoutUser,name='logout'),
    path('finalreg.html', views.finalreg, name='finalreg'),
    path('updateData/<int:EmpCode>', views.updateData, name='updateData'),
    path('final/<int:EmpCode>', views.final, name='final'),
    path('detail',views.det,name='det'),
    path('first',views.first,name='first'),
    # path('refid',views.refid,name='refid'),
]

tourlog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator

class Datas(models.Model): 
    EmpCode= models.IntegerField(primary_key=True)
    Name = models.CharField(max_length=100)
    SALUTATION_CHOICES = [
        ('Mr', 'Mr'),
        ('Ms', 'Ms'),
    ]
    salutation = models.CharField(max_length=2, choices=SALUTATION_CHOICES,null=True)    
    Desg = models.CharField(max_length=50)
    Grade_Pay = models.CharField(max_length=50)  
    Age=models.IntegerField()
    Email_ID=models.CharField(max_length=100)
    Phone = models.CharField(max_length=10,default='')
    Mobile=models.IntegerField()
    Office_Address=models.CharField(max_length=100)
    Purpose_of_Tour=models.CharField(max_length=100)
    Project_Expenditure = models.BooleanField(default=False)
    NICSI_Expenditure = models.BooleanField(default=False)
    Project_No=models.CharField(max_length=50)
    no = models.BooleanField(default=False)
    yes = models.BooleanField(default=False)
    Rs = models.CharField(max_length=100, null=True, blank=True)
    travel_date1 = models.CharField(max_length=255,default='')
    from_place1 = models.CharField(max_length=255,default='')
    to_place1 = models.CharField(max_length=255,default='')
    mode_of_travel1 = models.CharField(max_length=255,default='')
    flight_number1 = models.CharField(max_length=20,default='')
    departure_date1 = models.CharField(max_length=255,default='')
    departure_time1 = models.CharField(max_length=255,default='')
    arrival_date1 = models.CharField(max_length=255,default='')
    arrival_time1 = models.CharField(max_length=255,default='')
    travel_date2 = models.CharField(max_length=255,default='')
    from_place2 = models.CharField(max_length=255,default='')
    to_place2 = models.CharField(max_length=255,default='')
    mode_of_travel2 = models.CharField(max_length=255,default='')
    flight_number2 = models.CharField(max_length=20,default='')
    departure_date2 = models.CharField(max_length=255,default='')
    departure_time2 = models.CharField(max_length=255,default='')
    arrival_date2 = models.CharField(max_length=255,default='')
    arrival_time2 = models.CharField(max_length=255,default='')
    travel_date3 = models.CharField(max_length=255,default='')
    from_place3 = models.CharField(max_length=255,default='')
    to_place3 = models.CharField(max_length=255,default='')
    mode_of_travel3 = models.CharField(max_length=255,default='')
    flight_number3 = models.CharField(max_length=20,default='')
    departure_date3 = models.CharField(max_length=255,default='')
    departure_time3 = models.CharField(max_length=255,default='')
    arrival_date3 = models.CharField(max_length=255,default='')
    arrival_time3 = models.CharField(max_length=255,default='')
    travel_date4 = models.CharField(max_length=255,default='')
    from_place4 = models.CharField(max_length=255,default='')
    to_place4 = models.CharField(max_length=255,default='')
    mode_of_travel4 = models.CharField(max_length=255,default='')
    flight_number4 = models.CharField(max_length=20,default='')
    departure_date4 = models.CharField(max_length=255,default='')
    departure_time4 = models.CharField(max_length=255,default='')
    arrival_date4 = models.CharField(max_length=255,default='')
    arrival_time4 = models.CharField(max_length=255,default='')
    travel_date5 = models.CharField(max_length=255,default='')
    from_place5 = models.CharField(max_length=255,default='')
    to_place5 = models.CharField(max_length=255,default='')
    mode_of_travel5 = models.CharField(max_length=255,default='')
    flight_number5 = models.CharField(max_length=20,default='')
    departure_date5 = models.CharField(max_length=255,default='')
    departure_time5 = models.CharField(max_length=255,default='')
    arrival_date5 = models.CharField(max_length=255,default='')
    arrival_time5 = models.CharField(max_length=255,default='')
    


class Detail(models.Model):
    Name = models.CharField(max_length=100)
    Emp = models.CharField(max_length=100)

tourlog/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Datas
from .models import Detail



class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']




class DatasForm(forms.ModelForm):
    class Meta:
        model = Datas
        fields = '__all__'  

class DetailForm(forms.ModelForm):
    class Meta:
        model = Detail
        fields = '__all__' 

tourlog/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest
from django.contrib.auth.forms import UserCreationForm
from django.forms import inlineformset_factory
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm
from .models import *
from .models import Datas
from .models import Detail
# import uuid
# import time
# from .utils import generate_unique_reference_id

#LOGIN FORM
def home(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        emp_id = request.POST.get('EMP_ID')  

        user = authenticate(request, username=username, password=password)

        if user is not None:
            # Check if emp_id exists in the database
            if Datas.objects.filter(EmpCode=emp_id).exists():
                login(request, user)
                # Redirect to one file if emp_id exists
                return render(request,"app/viewreg.html",{'EmpCode':emp_id})
            else:
                # Redirect to another file if emp_id doesn't exist
                return render(request,"app/reg.html")
        else:
            messages.error(request, 'Username or Password is incorrect')

    return render(request, "app/loginn.html")

#logout
def logoutUser(request):
    logout(request)
    return redirect('home')

#Signup
def signup(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been created')
            return redirect('home')

    context = {'form': form}
    return render(request, "app/signup.html", context)


#Update
def updateData(request,EmpCode):
    myd=Datas.objects.get(EmpCode=EmpCode)
    return render(request,'app/update.html',{'data':myd})

#Finalview
def final(request,EmpCode):
    myd=Datas.objects.get(EmpCode=EmpCode)
    return render(request,'app/finalreg.html',{'data':myd})

from .models import Datas  
#Reg
def reg(request):
    latest_entry = None  # Initialize latest_entry as None
    
    if request.method == 'POST':
        code = request.POST.get('code')
        name = request.POST.get('name')
        salutation = request.POST.get('salutation')
        des = request.POST.get('des')
        pay = request.POST.get('pay')
        age = request.POST.get('age')
        ename = request.POST.get('ename')
        ph = request.POST.get('ph')
        mob = request.POST.get('mob')
        addr = request.POST.get('addr')
        pt = request.POST.get('pt')
        exp = 'exp' in request.POST  # Will be True if 'exp' is present
        pexp = 'pexp' in request.POST
        pn = request.POST.get('pn')
        no = 'no' in request.POST  # Will be True if 'no' is present
        yes = 'yes' in request.POST
        rs = request.POST.get('rs')
        travel_date1_str = request.POST.get('travel_date1')
        from_place1 = request.POST.get('from_place1')
        to_place1 = request.POST.get('to_place1')
        mode_of_travel1 = request.POST.get('mode_of_travel1')
        flight_number1 = request.POST.get('flight_number1')
        departure_date1_str = request.POST.get('departure_date1')
        departure_time1_str = request.POST.get('departure_time1')
        arrival_date1_str = request.POST.get('arrival_date1')
        arrival_time1_str = request.POST.get('arrival_time1')
        travel_date2_str = request.POST.get('travel_date2')
        from_place2 = request.POST.get('from_place2')
        to_place2 = request.POST.get('to_place2')
        mode_of_travel2 = request.POST.get('mode_of_travel2')
        flight_number2 = request.POST.get('flight_number2')
        departure_date2_str = request.POST.get('departure_date2')
        departure_time2_str = request.POST.get('departure_time2')
        arrival_date2_str = request.POST.get('arrival_date2')
        arrival_time2_str = request.POST.get('arrival_time2')
        travel_date3_str = request.POST.get('travel_date3')
        from_place3 = request.POST.get('from_place3')
        to_place3 = request.POST.get('to_place3')
        mode_of_travel3 = request.POST.get('mode_of_travel3')
        flight_number3 = request.POST.get('flight_number3')
        departure_date3_str = request.POST.get('departure_date3')
        departure_time3_str = request.POST.get('departure_time3')
        arrival_date3_str = request.POST.get('arrival_date3')
        arrival_time3_str = request.POST.get('arrival_time3')
        travel_date4_str = request.POST.get('travel_date4')
        from_place4 = request.POST.get('from_place4')
        to_place4 = request.POST.get('to_place4')
        mode_of_travel4 = request.POST.get('mode_of_travel4')
        flight_number4 = request.POST.get('flight_number4')
        departure_date4_str = request.POST.get('departure_date4')
        departure_time4_str = request.POST.get('departure_time4')
        arrival_date4_str = request.POST.get('arrival_date4')
        arrival_time4_str = request.POST.get('arrival_time4')
        travel_date5_str = request.POST.get('travel_date5')
        from_place5 = request.POST.get('from_place5')
        to_place5 = request.POST.get('to_place5')
        mode_of_travel5 = request.POST.get('mode_of_travel5')
        flight_number5 = request.POST.get('flight_number5')
        departure_date5_str = request.POST.get('departure_date5')
        departure_time5_str = request.POST.get('departure_time5')
        arrival_date5_str = request.POST.get('arrival_date5')
        arrival_time5_str = request.POST.get('arrival_time5')

        # Check if 'rs' is provided and not empty
        if rs:
            rs_value = rs  
        else:
            rs_value = None  

        # Create a new Datas object
        obj = Datas(
            EmpCode=code,
            Name=name,
            salutation=salutation,
            Desg=des,
            Grade_Pay=pay,
            Age=age,
            Email_ID=ename,
            Phone=ph,
            Mobile=mob,
            Office_Address=addr,
            Purpose_of_Tour=pt,
            NICSI_Expenditure=exp,
            Project_Expenditure=pexp,
            Project_No=pn,
            no=no,
            yes=yes,
            Rs=rs_value,  # Use the determined rs_value
            travel_date1=travel_date1_str,
            from_place1=from_place1,
            to_place1=to_place1,
            mode_of_travel1=mode_of_travel1,
            flight_number1=flight_number1,
            departure_date1=departure_date1_str,
            departure_time1=departure_time1_str,
            arrival_date1=arrival_date1_str,
            arrival_time1=arrival_time1_str,
            travel_date2=travel_date2_str,
            from_place2=from_place2,
            to_place2=to_place2,
            mode_of_travel2=mode_of_travel2,
            flight_number2=flight_number2,
            departure_date2=departure_date2_str,
            departure_time2=departure_time2_str,
            arrival_date2=arrival_date2_str,
            arrival_time2=arrival_time2_str,
            travel_date3=travel_date3_str,
            from_place3=from_place3,
            to_place3=to_place3,
            mode_of_travel3=mode_of_travel3,
            flight_number3=flight_number3,
            departure_date3=departure_date3_str,
            departure_time3=departure_time3_str,
            arrival_date3=arrival_date3_str,
            arrival_time3=arrival_time3_str,
            travel_date4=travel_date4_str,
            from_place4=from_place4,
            to_place4=to_place4,
            mode_of_travel4=mode_of_travel4,
            flight_number4=flight_number4,
            departure_date4=departure_date4_str,
            departure_time4=departure_time4_str,
            arrival_date4=arrival_date4_str,
            arrival_time4=arrival_time4_str,
            travel_date5=travel_date5_str,
            from_place5=from_place5,
            to_place5=to_place5,
            mode_of_travel5=mode_of_travel5,
            flight_number5=flight_number5,
            departure_date5=departure_date5_str,
            departure_time5=departure_time5_str,
            arrival_date5=arrival_date5_str,
            arrival_time5=arrival_time5_str,
        )

        # Save the object to the database
        obj.save()

        # Set latest_entry to the newly created object
        latest_entry = obj

    return render(request, "app/reg.html", {'latest_entry':latest_entry})



def finalreg(request):
    return render(request,"app/finalreg.html")


def first(request):
    return render(request,"app/first.html")

# def refid():
#     # Generate a unique reference ID using UUID
#     return str(uuid.uuid4().hex[:12])


def det(request):
    if request.method == 'POST':
        # Retrieve data from the POST request
        Name = request.POST.get('Name')
        Emp = request.POST.get('Emp')
        obj = Detail(
            Name=Name,
            Emp=Emp,
        )

        obj.save()
    return render(request,"app/detail.html")

tourlog/templates/app/demoreg.html
<h1>Register</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{form.username.label}}
    {{form.username}}

    {{form.email.label}}
    {{form.email}}

    
    {{form.password1.label}}
    {{form.password1}}

    
    {{form.password2.label}}
    {{form.password2}}

    <p><input type="submit" value="Create User"></p>
</form>

tourlog/templates/app/finalreg.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tour Log Sheet</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="css/base.css">
  <style>
    body {
    margin: 0;
  }

  .container {
    background-color: #ffffff;
    margin-top: 20px;
    padding: 10px;
    margin-left: 15px;
    width: 100%;
  }
    /* .container {
        background-color: #ffffff;
        margin-top: 20px ;
        padding: 10px;
        margin-left: 15px;
        width: 300%;
      } */
    .row {
      background-color: rgb(255, 255, 255);
      padding: 1px;
    }
    .col,
    .col-8,
    .col-6,
    .col-4,
    .col-md-8,
    .col-1,
    .col-3,
    .col-md-4 {
      background-color: rgb(255, 255, 255);
      padding: 10px;
    }
    table {
        /* background-color: rgb(255, 255, 255); */
        background-color: #ffffff;
        margin-left: 15px;
        width: 5px;
        /* padding: 5px; */
        /* border: 1px solid rgb(6, 6, 6); */
      }
    .col-2 {
      text-align-last: left;
    }
    .col-auto {
      padding: 1px;
    }
    .input[type="number"] {
      width: 40%;
      font-size: 10px;
    }
    .input[type="text"] {
      width: 50%;
      font-size: 10px;
    }
    .oate {
      text-align-last: right;
      font-size: 10px;
    }
    .cert {
      text-align-last: left;
    }
    .form-row {
      display: flex;
      align-items: center;
    }
    .custom-size {
      flex: 1;
      width: 30%;
    }
    .custom-des {
      flex: 1;
      width: 30%;
      height: 50%;
    }
    .table th,
    .table td {
      border: 1px solid #000;
    }
    .top-right-button {
        margin-left: 5px;
        position: absolute;
        top: 0.5px;
        bottom: 2500px;
        right: 0px;
        margin-right: 10px;

      }
      .smaller-table {
            width: 80%; 
            max-width: none;
            font-size: 8pt; 
            height: 4%;
        }
  </style>
</head>
<body>
  <div class="container">
    <form action="" method="POST" autocomplete="off">
        {% csrf_token %}
    <div class="row">
      <div class="col">
        <label for="code">Emp.Code</label>
        <input type="number" value="{{data.EmpCode}}"  id="code" class="custom-des">
      </div>
      <div class="col-3">
        <div class="form-row">
          <label for="name">Name:</label>
          <form>
            <select name="salutation">
                <option value="{{data.salutation}}">Mr</option>
                <option value="{{data.salutation}}">Ms</option>
            </select>
          </form>
          <input type="text" id="name" value="{{data.Name}}" class="input">
        </div>
      </div>
      <div class="col">
        <label for="des">Desg:</label>
        <input type="text" value="{{data.Desg}}" id="des" class="custom-size1">
      </div>
      <div class="col">
        <label for="pay">Grade Pay:</label>
        <input type="text" value="{{data.Grade_Pay}}" id="pay" class="custom-size2">
      </div>
      <div class="col">
        <label for="age">Age:</label>
        <input type="number"  value="{{data.Age}}" id="age" class="custom-des">
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <label for="id">Email ID:</label>
        <input type="text" value="{{data.Email_ID}}" id="id" class="input">
      </div>
      <div class="col">
        <label for="ph">Phone (off):</label>
        <input type="number" value="{{data.Phone}}" id="ph" class="custom-size2">
      </div>
      <div class="col">
        <label for="mob">Mobile:</label>
        <input type="number" value="{{data.Mobile}}" id="mob" class="custom-size2">
      </div>
    </div>
    <div class="row">
      <div class="col">
        <label for="addr">Office Address:</label>
        <input type="text" value="{{data.Office_Address}}" id="addr" class="input">
      </div>
    </div>
    <div class="row">
      <div class="col">
        <label for="pt">Purpose of Tour:</label>
        <input type="text" value="{{data.Purpose_of_Tour}}" id="pt" class="input">
      </div>
    </div>
    <div class="row">
      <div class="form-row">
        <div class="col">
            <label for="name">Budget Head:</label>
          </div>
        <div class="col-4">
            <input type="radio" value="NICSI_Expenditure" id="exp" {% if data.NICSI_Expenditure %}checked{% endif %}>NICSI Expenditure<br>
            <div class="form-row">
              <input type="radio" value="Project_Expenditure" id="pexp" {% if data.Project_Expenditure %}checked{% endif %}>Project Expenditure&nbsp;
              <label for="pn">Project No</label>
              <input type="text" id="pn" class="custom-size" value="{{ data.Project_No }}">
            </div>
        </div>
        <div class="col"></div>
        <div class="col">
          <label for="name">Advance Required:</label>
        </div>
        <div class="col-3">
            <br>
            <input type="radio" name="advance_required" id="no" value="no" {% if data.no %}checked{% endif %}> NO<br>
            <input type="radio" name="advance_required" id="yes" value="yes" {% if data.yes %}checked{% endif %}> YES &nbsp;
            <label for="rs">Rs</label>
            <input type="number" name="rs" class="custom-size" value="{{ data.Rs }}">
          </div>
        </div>
      </div>
    </div>
    <br>
    <!-- <div class="table"> -->
      <table class="table tab smaller-table">
          <thead>
            <tr>
              <th>Date of Travel</th>
              <th>From (Place)</th>
              <th>To (Place)</th>
              <th>Mode of Travel</th>
              <th>Flight No.</th>
              <th>Dprt. Date</th>
              <th>Dprt. Time</th>
              <th>Arrival Date</th>
              <th>Arrival Time</th>
            </tr>
          </thead>
          <tbody>
            <!-- Rows with borders -->
            <tr>
                <td><input type="date" name="travel_date1" id="travel_date1" value="{{ data.travel_date1 }}"></td>
                <td><input type="text" name="from_place1"value="{{ data.from_place1 }}"></td>
                <td><input type="text" name="to_place1" value="{{ data.to_place1 }}"></td>
                <td><input type="text" name="mode_of_travel1"value="{{ data.mode_of_travel1 }}"></td>
                <td><input type="text" name="flight_number1"value="{{ data.flight_number1 }}"></td>
                <td><input type="date" name="departure_date1" id="departure_date1"value="{{ data.departure_date1 }}"></td>
                <td><input type="time" name="departure_time1"value="{{ data.departure_time1 }}"></td>
                <td><input type="date" name="arrival_date1" id="arrival_date1"value="{{ data.arrival_date1 }}"></td>
                <td><input type="time" name="arrival_time1"value="{{ data.arrival_time1 }}"></td>
            </tr>
            <tr>
                <td><input type="date" name="travel_date2" id="travel_date2" value="{{ data.travel_date2 }}"></td>
                <td><input type="text" name="from_place2"value="{{ data.from_place2 }}"></td>
                <td><input type="text" name="to_place2"value="{{ data.to_place2 }}"></td>
                <td><input type="text" name="mode_of_travel2"value="{{ data.mode_of_travel2 }}"></td>
                <td><input type="text" name="flight_number2"value="{{ data.flight_number2 }}"></td>
                <td><input type="date" name="departure_date2" id="departure_date2"value="{{ data.departure_date2 }}"></td>
                <td><input type="time" name="departure_time2"value="{{ data.departure_time2 }}"></td>
                <td><input type="date" name="arrival_date2" id="arrival_date2"value="{{ data.arrival_date2 }}"></td>
                <td><input type="time" name="arrival_time2"value="{{ data.arrival_time2 }}"></td>
            </tr>
            <tr>
                <td><input type="date" name="travel_date3" id="travel_date3" value="{{ data.travel_date3 }}"></td>
                <td><input type="text" name="from_place3"value="{{ data.from_place3 }}"></td>
                <td><input type="text" name="to_place3"value="{{ data.to_place3 }}"></td>
                <td><input type="text" name="mode_of_travel3"value="{{ data.mode_of_travel3 }}"></td>
                <td><input type="text" name="flight_number3"value="{{ data.flight_number3 }}"></td>
                <td><input type="date" name="departure_date3" id="departure_date3"value="{{ data.departure_date3 }}"></td>
                <td><input type="time" name="departure_time3"value="{{ data.departure_time3 }}"></td>
                <td><input type="date" name="arrival_date3" id="arrival_date3"value="{{ data.arrival_date3 }}"></td>
                <td><input type="time" name="arrival_time3"value="{{ data.arrival_time3 }}"></td>
            </tr>
            <tr>
                <td><input type="date" name="travel_date4" id="travel_date4" value="{{ data.travel_date4 }}"></td>
                <td><input type="text" name="from_place4"value="{{ data.from_place4 }}"></td>
                <td><input type="text" name="to_place4"value="{{ data.to_place4 }}"></td>
                <td><input type="text" name="mode_of_travel4"value="{{ data.mode_of_travel4 }}"></td>
                <td><input type="text" name="flight_number4"value="{{ data.flight_number4 }}"></td>
                <td><input type="date" name="departure_date4" id="departure_date4"value="{{ data.departure_date4 }}"></td>
                <td><input type="time" name="departure_time4"value="{{ data.departure_time4 }}"></td>
                <td><input type="date" name="arrival_date4" id="arrival_date4"value="{{ data.arrival_date4 }}"></td>
                <td><input type="time" name="arrival_time4"value="{{ data.arrival_time4 }}"></td>
            </tr>
            <tr>
                <td><input type="date" name="travel_date5" id="travel_date5" value="{{ data.travel_date5 }}"></td>
                <td><input type="text" name="from_place5"value="{{ data.from_place5 }}"></td>
                <td><input type="text" name="to_place5"value="{{ data.to_place5 }}"></td>
                <td><input type="text" name="mode_of_travel5"value="{{ data.mode_of_travel5 }}"></td>
                <td><input type="text" name="flight_number5"value="{{ data.flight_number5 }}"></td>
                <td><input type="date" name="departure_date5" id="departure_date5"value="{{ data.departure_date5 }}"></td>
                <td><input type="time" name="departure_time5"value="{{ data.departure_time5 }}"></td>
                <td><input type="date" name="arrival_date5" id="arrival_date5"value="{{ data.arrival_date5 }}"></td>
                <td><input type="time" name="arrival_time5"value="{{ data.arrival_time5 }}"></td>
            </tr>
        </tbody>
    </table>
    <br>
    <div class="oate">
      <label>I undertake that I shall submit TA/DA bill along with boarding passes to NICSI within 15 days of tour</label> 
      <br>
      <label>completion. Beyond 15 days, bills of booking agency for air travel can be settled by NICS at my risk</label>
      <br>
      <br>
      <label>Sign of officer</label>
      <br>
      <input type="file" id="uploadedFile" accept="image/*">
        <div id="imageContainer"></div>
        
        <script>
          const fileInput = document.getElementById('uploadedFile');
          const imageContainer = document.getElementById('imageContainer');
        
          fileInput.addEventListener('change', (event) => {
              const file = event.target.files[0];
              const reader = new FileReader();
        
              reader.onload = (e) => {
                  const img = document.createElement('img');
                  img.src = e.target.result;
                  img.width=200;
                  // img.height=100;
                  imageContainer.innerHTML = ''; 
                  imageContainer.appendChild(img);
              };
        
              reader.readAsDataURL(file);
          });
        </script>

        <br>
        <label >Sign of officer</label>
        <br>
        <div class="cert">
          <label>Certifed that the funds are available in project</label>
          <br>
          <br>
          <label>Approval/comments</label>
          <br>
          <br>
        </div>
        <div class="row clr">
          <div class="col-2">
            <label>Name:</label><br>
            <label>Emp. Code:</label>
          </div>
          <div class="col-1 clr">
            <label>Designation:</label>
          </div>
          <div class="col clr"></div>
          <div class="col-1 clr">
            <label class="lab">DG (NIC)</label><br>
            <label class="lab1">(For nic Officer)</label>
          </div>
        </div>
        
        <button class="btn btn-link top-right-button">
        <a class="link" href="{% url 'tourlog:logout' %}">Logout</a>
        </button>
        <button id="printButton">Print This Page</button>
        
        
        <script>
          
          document.getElementById("printButton").addEventListener("click", function() {
              
              window.print();
          });
        </script>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        </div>
        </body>
        </html>

tourlog/templates/app/first.html
<html>
    <body>
        <script>
            // Get the EMP_ID value from a Django context variable
            var empId = {{ EmpCode }};
            
            // Construct the URL using the empId variable
            var updateUrl = `http://127.0.0.1:8000/final/${empId}`;
          
            // Redirect to the constructed URL
            window.location.href = updateUrl;
          </script>
    </body>
</html>